In [11]:
import pandas as pd
import numpy as np
import math

In [12]:
df = pd.read_csv("test_scores.csv")
df.head(3)

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81

In [16]:
x = np.array(df.math)
y = np.array(df.cs)
x, y

(array([92, 56, 88, 70, 80, 49, 65, 35, 66, 67]),
 array([98, 68, 81, 80, 83, 52, 66, 30, 68, 73]))

In [53]:
def gradient_descent(x, y):
    m_curr = b_curr = 0
    learning_rate = 0.0002
    iteration = 1
    n = len(x)
    prev_cost = 0
    while(1):
        y_predicted = m_curr * x + b_curr
        cost = (1 / n) * sum([val ** 2 for val in (y - y_predicted)])
        md = -(2 / n) * sum(x * (y - y_predicted))
        bd = -(2 / n) * sum(y - y_predicted)
        m_curr = m_curr - learning_rate * md
        b_curr = b_curr - learning_rate * bd
        if(math.isclose(cost, prev_cost, rel_tol=1e-20)):
            break
        prev_cost = cost
        if iteration % 1000 == 0:
            print(f"Iteration {iteration}, m: {m_curr:.4f}, b: {b_curr:.4f}, cost: {cost:.6f}")
        iteration += 1
    return m_curr, b_curr, iteration

In [55]:
m, b, itr = gradient_descent(x, y)
print(f"m: {m}, b: {b}, iteration: {itr}")

Iteration 1000, m: 1.0439, b: 0.0579, cost: 31.802556
Iteration 2000, m: 1.0434, b: 0.1000, cost: 31.793668
Iteration 3000, m: 1.0428, b: 0.1412, cost: 31.785179
Iteration 4000, m: 1.0422, b: 0.1815, cost: 31.777071
Iteration 5000, m: 1.0416, b: 0.2208, cost: 31.769327
Iteration 6000, m: 1.0411, b: 0.2593, cost: 31.761930
Iteration 7000, m: 1.0406, b: 0.2969, cost: 31.754866
Iteration 8000, m: 1.0401, b: 0.3336, cost: 31.748118
Iteration 9000, m: 1.0395, b: 0.3695, cost: 31.741673
Iteration 10000, m: 1.0391, b: 0.4046, cost: 31.735518
Iteration 11000, m: 1.0386, b: 0.4389, cost: 31.729638
Iteration 12000, m: 1.0381, b: 0.4724, cost: 31.724023
Iteration 13000, m: 1.0376, b: 0.5051, cost: 31.718659
Iteration 14000, m: 1.0372, b: 0.5371, cost: 31.713537
Iteration 15000, m: 1.0367, b: 0.5684, cost: 31.708644
Iteration 16000, m: 1.0363, b: 0.5990, cost: 31.703971
Iteration 17000, m: 1.0359, b: 0.6289, cost: 31.699507
Iteration 18000, m: 1.0355, b: 0.6581, cost: 31.695244
Iteration 19000, m:

In [ ]:
from sklearn.linear_model import LinearRegression

In [59]:
def usingLR(df):
    reg = LinearRegression()
    reg.fit(df[["math"]], df.cs)
    return reg.coef_, reg.intercept_

In [60]:
usingLR(df)

(array([1.01773624]), 1.9152193111569034)